FROM debian:11

ENV RUBY_VERSION 2.7.2
ENV BUNDLER_VERSION 1.16.6

RUN apt update && apt install -y procps curl gnupg2 lsb-release ca-certificates 

# Install redis
RUN curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list
RUN apt update && apt install -y redis

# Install build essential 
RUN apt install -y build-essential git

# Install dependencies for ruby
RUN apt install -y gawk autoconf automake bison libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev pkg-config sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev

# clone & build project
RUN adduser --disabled-password --gecos '' tester
COPY . /home/tester/redis-cluster-proxy
WORKDIR /home/tester/redis-cluster-proxy
RUN chown -R tester:tester /home/tester/redis-cluster-proxy
USER tester
RUN make

# Install ruby for tests
RUN curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
RUN curl -sSL https://rvm.io/pkuczynski.asc |gpg2 --import -
RUN curl -sSL https://get.rvm.io | bash -s stable
RUN /bin/bash -c "source ~/.rvm/scripts/rvm && \
                  rvm install ${RUBY_VERSION} && \
                  rvm use ${RUBY_VERSION} --default && \
                  gem install bundler:${BUNDLER_VERSION}"

ENTRYPOINT ["/bin/bash", "-c", "source ~/.rvm/scripts/rvm && \"$@\"", "-s"]








